### ISSUE TITLE
Creating one collection per day

### ISSUE THREAD

**Issue by abrasat** [ChangemakerStudios/serilog-sinks-mongodb#43]
Would be possible to configure the serilog mongodb sink to create one collection per day, and to keep for instance the logs from the last 30 days (the older collections should be removed) ?
Are there any samples available about how to implement such a feature ?

**Comment by Jaben** [comment]
This would be possible: a sort of "rolling" feature. But I fear it's a bit out of scope of features this sink should provide.

**Comment by Revazashvili** [comment]
i just opened PR for this issue.

https://github.com/ChangemakerStudios/serilog-sinks-mongodb/pull/77

**Comment by Jaben** [comment]
PR is merged. Releasing latest.
