### ISSUE TITLE
How to Set TTL in Serilog Sink MongoDB

### ISSUE THREAD

**Issue by fireloudapp** [ChangemakerStudios/serilog-sinks-mongodb#67]
How can I set expiration of log data in MongoDB through serilog sink. ?

MongoDB has the functionality of seeing this for each document, but do we have this option through serilog sinks mongodb ?

[Expiry Data in MogoDB](https://docs.mongodb.com/manual/tutorial/expire-data/) 

Thanks in advance.

**Comment by Jaben** [comment]
Feature is in latest pre-release nuget push: Serilog.Sinks.MongoDB.5.1.2-dev-00124.

Please give it a shot!

**Comment by meghasinghal1** [comment]
Hi Jaben,

What is the settings which needs to be configured in code to set the expiry of serilog document?

Thanks
