### ISSUE TITLE
[Quesion] Can I incorporateyour wokr in my Log Viewer?

### ISSUE THREAD

**Issue by LiorBanai** [ChangemakerStudios/serilog-sinks-mongodb#71]
Hi,
I have log viewer (https://github.com/Analogy-LogViewer). One of the providers is Serilog.
I was wondering if I can use your code to create mongoDb data provider..

**Comment by Jaben** [comment]
Not sure what you're question is. If your asking if you can use this project in your project? The answer is yes.

**Comment by LiorBanai** [comment]
yes. thank you
