### ISSUE TITLE
New organization required for this repository

### ISSUE THREAD

**Issue by nblumhardt** [ChangemakerStudios/serilog-sinks-mongodb#72]
Hi @serilog/reviewers-mongodb 👋  (... a bit of a form letter - greetings @Jaben :-))

Via https://github.com/serilog/serilog/issues/1627 - we're unbundling the `serilog` organization to help distribute the effort involved in managing the various Serilog sub-projects. The `serilog` organization will now only manage the fundamental sinks and other packages that the rest of the ecosystem builds upon.

If this package is actively maintained, it can be moved to a new organization managed by the maintainers. Otherwise, it can move to the `serilog-archive` parking lot, from where we hope a new community-run fork might spring from in the future 🌷 .

Let me know if you're a maintainer and keen to continue this project under a new org; otherwise, I'll shuffle things around and move this one to the archive.

Thanks!

**Comment by Jaben** [comment]
Hey Nick! -- yeah, this can be migrated to my org: https://github.com/ChangemakerStudios

**Comment by nblumhardt** [comment]
That's great, thanks Jaben.

I'm getting:

> ChangemakerStudios/serilog-sinks-mongodb already exists and You don’t have the permission to create public repositories on ChangemakerStudios 

May need to rename your existing fork? 🤔

**Comment by nblumhardt** [comment]
@Jaben I've made you an admin of the repository so you should now be able to transfer it over. Let me know if you need a hand. 

Also, would be good to confirm which NuGet account should be made the new owner.

**Comment by Jaben** [comment]
Done! 🕺 

Yeah, nuget account is just "Jaben" -- Thank you!

**Comment by nblumhardt** [comment]
Great! NuGet ownership added now, but still need a hand from the NuGet team to remove the `serilog` org as an owner there.
