### ISSUE TITLE
how to custom message template

### ISSUE THREAD

**Issue by wuzhenda** [ChangemakerStudios/serilog-sinks-mongodb#73]
if I want to add property like "deviceId" in the document, how to implement it?
like this
![image](https://user-images.githubusercontent.com/1329895/164435183-1a4fda1d-36b3-4151-a8f8-5cb91fbc931a.png)

**Comment by Jaben** [comment]
Switch to using the MongoDBBson() logging.

**Comment by wuzhenda** [comment]
got it.
