### ISSUE TITLE
Multiple MongoDB subloggers without collection race condition

### ISSUE THREAD

**Issue by BloodLustAlpaca** [ChangemakerStudios/serilog-sinks-mongodb#76]
I have two mongodb subloggers logging to the same collection. I am using two to handle some filter logic. If the collection is not created one of the two subloggers loggers doesnt get to log. I assume this is due to the batch emit. It might be reading two mongodb sinks and sees they need to create the collection, adds them to the batch and tries to create it twice. I am new to this so I might just be missing something simple. This should only apply to using two subloggers to the same collection on first batch without a collection made already.

![Mongodb_race](https://user-images.githubusercontent.com/14988822/168389109-9cbc010c-0db0-4eda-9afc-64e5190684ad.PNG)

**Comment by wuzhenda** [comment]
the two subloggers  start at the same times?

**Comment by Jaben** [comment]
@BloodLustAlpaca please post the WHOLE exception. What exception is being thrown?

**Comment by Jaben** [comment]
@BloodLustAlpaca Committed a fix for this problem -- hopefully now it works.
