### ISSUE TITLE
need a queue to cache logs

### ISSUE THREAD

**Issue by wuzhenda** [ChangemakerStudios/serilog-sinks-mongodb#79]
the performance is not good enough,
maybe better to add a queue to cache more logs and write to db once for all.

**Comment by Jaben** [comment]
The current sink uses [PeriodicBatchingSink](https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs) which does batching and queuing.

If you feel you have a better method, feel free to submit a Pull Request.

**Comment by Jaben** [comment]
Latest adds the ability to configure the "Insert Options" for MongoDb. So you can turn off Validation and it should be faster:

```cfg.ConfigureInsertOptions(s => s.BypassDocumentValidation = true);```

**Comment by Jaben** [comment]
That feature is in v5.2.2 -- closing this issue for now.
