### ISSUE TITLE
How to set expiry on MongoDB document -  Can someone please share working example of it?

### ISSUE THREAD

**Issue by meghasinghal1** [ChangemakerStudios/serilog-sinks-mongodb#81]
Hi Team,

Need a quick help please on log document which is getting created in MongoDB. 

How to set expiry on MongoDB document so it can be deleted automatically? I read that, it was rolled out part of 5.x version, Could someone please share a working example of it?

Thanks

**Comment by Jaben** [comment]
```csharp
	var log = new Serilog.LoggerConfiguration().WriteTo.MongoDBBson(cfg => {
		cfg.SetCollectionName("log");
                // set the TTL on the log entry to 5 minutes expiration
		cfg.SetExpireTTL(TimeSpan.FromMinutes(5));
        }).MinimumLevel.Verbose().CreateLogger();
````

**Comment by Jaben** [comment]
Closing as I provided an example.
