### ISSUE TITLE
Useless fields are saving in mongodb

### ISSUE THREAD

**Issue by aliaa** [ChangemakerStudios/serilog-sinks-mongodb#82]
`MessageTemplate` and `UtcTimestamp` are redundant and useless fields to be saved in my opinion which makes storage cost double.

**Comment by Jaben** [comment]
In the "Legacy" sink or the new Bson sink? In the new Bson sink, I'll add the option to exclude the MessageTemplate.

**Comment by trlthiago** [comment]
Hi !

Is there a deadline to publish this update on Nuget? 

Tks.

**Comment by Jaben** [comment]
v6 has this change. Reopen this issue if you're still having a problem.
