### ISSUE TITLE
MongoDBSinkConfiguration.SetMongoDatabase giving CS0012 

### ISSUE THREAD

**Issue by danielfewster** [ChangemakerStudios/serilog-sinks-mongodb#88]
I'm trying to configure my MongoDB Sink, but the following code throws:
Error (active)	CS0012	The type 'IMongoDatabase' is defined in an assembly that is not referenced. You must add a reference to assembly 'MongoDB.Driver, Version=2.19.0.0, Culture=neutral, PublicKeyToken=null'.
`new LoggerConfiguration()
                .WriteTo.MongoDBBson(cfg =>
                {
                    cfg.SetMongoDatabase(myDB); // NOTE: SetMongoDatabase ERROR: CS0012
                    cfg.SetRollingInternal(RollingInterval.Month);
                })
                .CreateLogger();`

**Comment by Jaben** [comment]
Released v6.0 right now -- should fix it.
