### ISSUE TITLE
Incompatible with Mongo release 2.28.0 due to strongly named assembly

### ISSUE THREAD

**Issue by aj-scram** [ChangemakerStudios/serilog-sinks-mongodb#89]
Strongly named assembly was introduced in Mongo.Bson 2.28.0 and its created a breaking change, such that this package can no longer be consumed.

see: 
- https://github.com/mongodb/mongo-csharp-driver/pull/1393
- https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/2265 (example of the problem)

Could you update and do a new release please?

**Comment by Jaben** [comment]
Released v6.0 right now -- should fix it.
