### ISSUE TITLE
MongoDB.Driver 3.0 changes MongoClientBase visibility to Internal

### ISSUE THREAD

**Issue by JKRaks** [ChangemakerStudios/serilog-sinks-mongodb#90]
I was able to log properly when I tried using 2.30, but when I updated the package to 3.0 it became unavailable. 

When printing logs it returns that MongoClientBase could not be found.

I checked the PR for MongoDB.Driver and found that it has been changed to internal.

https://github.com/mongodb/mongo-csharp-driver/pull/1461#discussion_r1785051354

**Comment by fatihmgenc** [comment]
I just faced with the same issue, moreover they removed the MongoClientBase and swithed to IMongoClient interface.
[mongodb/mongo-csharp-driver/commit/dacd83ce](https://github.com/mongodb/mongo-csharp-driver/commit/dacd83ce)

**Comment by ragasjohn** [comment]
Hello I have the same issue

My error is _Could not load type 'MongoDB.Driver.MongoClientBase' from assembly 'MongoDB.Driver, Version=3.0.0.0_

**Comment by Jaben** [comment]
Just released v7.0 that uses MongoDB 3.0.
